### ISSUE TITLE
Class on anchor wrapper

### ISSUE THREAD

**Issue by krogsgard** [justintadlock/get-the-image#13]
There's an attribute for adding a class to Get The Image, but no way to customize the anchor tag wrapper. It'd be nice to have a class there: https://github.com/justintadlock/get-the-image/blob/master/get-the-image.php#L712

Twenty Fifteen uses what I think is a relative standard 'post-thumbnail' class on the anchor tag or featured image wrapper (archive vs singular): https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfifteen/inc/template-tags.php#L196

 I'd be up for just making that a class. But otherwise, at least an attribute to the args to be able to customize this?

I often have to not link to post via an attribute and then manually build this wrapper however I want it, which seems silly when a class could be what I need.

**Comment by justintadlock** [comment]
It should be simple enough to do.  We'd just need a `link_class` argument.  It's just a few lines of extra code for a useful feature.

**Comment by justintadlock** [comment]
All done!  Give it a go and let me know if you hit any issues.
