### ISSUE TITLE
WP Retina 2x

### ISSUE THREAD

**Issue by nvartolomei** [justintadlock/get-the-image#14]
Hello,
Have anyone made this plugin/function compatible with WP Retina 2x plugin?

**Comment by nvartolomei** [comment]
Looks like I was able to track down the issue, I enabled log for WP Retina 2x and saw this:
```
2015-07-15 13:25:09: * HTML REWRITE FOR PICTUREFILL
2015-07-15 13:25:09: The img tag '<img src="http://wp.dev/content/uploads/sites/35/2015/07/doctype-hi-res-250x140.jpg" alt="SONY DSC" class="Thumbnail thumbnail loop-main" />' was rewritten to '<img alt="SONY DSC" class="Thumbnail thumbnail loop-main" srcset="http://wp.dev/content/uploads/sites/35/2015/07/doctype-hi-res-250x140.jpg, http://wp.dev/content/uploads/sites/35/2015/07/doctype-hi-res-250x140@2x.jpg 2x" />'
2015-07-15 13:25:09: 1/1 were replaced.
```

But actually the image was not replaced, after half hour of investigation I found that WP Retina 2x plugin works by buffering HTML output generated by WordPress and then parsing it using a library called simplehtmldom for `<img>` tags. Then it if retina versions of those images are available by checking `src` attributes for every `<img>` tag found on page and then replaces those tags, now the issue is caused because input html is different from parsed html.

Why it is different? Because of this code in `get-get-image`:

```
/* Join all the classes into a single string and make sure there are no duplicates. */
$class = join( ' ', array_unique( $classes ) );
```
This code ads a trailing space, which simplehtmldom removes from class attribute value and matching could not be done.

This issue in fact is in WP Retina 2x, but thought this might be interesting there too.

PS. This issue is only for Picturefill method, as far as I know.

**Comment by justintadlock** [comment]
This code doesn't add a trailing space.  A `join()` call only joins the pieces with the `' '` in between.  It won't add any after the last item.

	/* Join all the classes into a single string and make sure there are no duplicates. */
	$class = join( ' ', array_unique( $classes ) );

There may be an issue under some circumstances where a space gets added some other way though.  I can't reproduce that on the latest branch though.  https://github.com/justintadlock/get-the-image/tree/1.1

Also, that branch has the `srcset` attribute built in, so there's no need for another plugin to do retina featured images.

I'm tempted to close this unless there's something actionable that needs to be done in GTI.

**Comment by nvartolomei** [comment]
Yeah, it's not the case in v1.1 anymore, I was using older version which joined image_class too without checking it's value, in case it was empty the result had a trailing whitespace, because `join( ' ', [ 'something', false ] )` results in `'something '`.

As I can see in v1.0, v1.1 (haven't checked others) you already verify the contents of image_class.
