### ISSUE TITLE
Attachment retrieval and 'scan' arg thumbnail size issue

### ISSUE THREAD

**Issue by ptrckvllnv** [justintadlock/get-the-image#15]
All the post was duplicated and can't get the attachment until I used the 'scan' arg and thumbnails was showed BUT.

Used code:

``<?php get_the_image(); ?>``

![blog and news](https://cloud.githubusercontent.com/assets/4774295/9585455/a6593d4c-5049-11e5-840c-f72b1bd03e5e.png)

------------------------------------------------------------------------------

Returns different image size from the set_post_thumbnail_size() and returns different image size from the first post - see it above, that's the correct thumbnail size.

Used code:

``<?php get_the_image( array( 'scan' => true, 'size' => 'post-thumbnail' ) ); ?>``

![blog and news 2](https://cloud.githubusercontent.com/assets/4774295/9585807/a3409248-504b-11e5-984b-71dbcaa865d2.png)

**Comment by justintadlock** [comment]
I'm not sure I understand.  Can you explain the issue in a bit more detail (with the screenshots, please)?

**Comment by ptrckvllnv** [comment]
Sorry, already fixed! Thanks.
